# Numpy 

numpy Lineer Cebir modülüdür. Bu nedenle matrislerle ilgili işlemlerden sorumludur. Tek boyutlu ve çok boyutlu dizi (array) yapsları bu modül ile oluşturularak Lineer Cebir yöntemleri ile kullanılabilir. 

Bu özelliğinden dolayı, Veri madenciliği, makine öğrenmesi ve veri analizi işlemlerinde etkin kullanılan bir modüldür. 

numpy' ın array yapısı, liste veri tipine göre daha küçük yer kaplar, array elemanlarına ulaşmak liste elemanlarına ulaşmaktan daha hızlıdır. Liste veri yapısı kullanılması durumunda gerekli işlemler için kendimiz modül ve fonksiyon yazmalıyız fakat bu bu modül ve fonksiyonlar halihazırda numpy içinde bulunmaktadır. 

numpy Anaconda ile hazır gelmektedir. Fakat eğer yüklü değilse conda promttan conda install numpy yazılarak ya da Python idle için pip install numpy yazılarak yüklenebilir. 

# numpy array yapısı

In [1]:
data_list = [1,2,3,4]
data_list

[1, 2, 3, 4]

In [2]:
import numpy as np

In [3]:
arr = np.array(data_list)
arr

array([1, 2, 3, 4])

In [6]:
data_list2 = [[1,2,3],[10,20,30],[100,200,300]]
arr2 = np.array(data_list2)
arr2

array([[  1,   2,   3],
       [ 10,  20,  30],
       [100, 200, 300]])

In [7]:
arr3 = np.array([1,2,3,4,5])
arr3

array([1, 2, 3, 4, 5])

In [8]:
arr3[0]

1

In [9]:
arr3[-1]

5

In [10]:
arr2

array([[  1,   2,   3],
       [ 10,  20,  30],
       [100, 200, 300]])

In [11]:
arr2[2,2]

300

In [13]:
arr2[0,2]

3

# numpy üzerinde metotlar 

In [14]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [15]:
np.arange(0,100,4)

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64,
       68, 72, 76, 80, 84, 88, 92, 96])

In [16]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [19]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

linspace metodu, girilen sayı aralığını üçüncü parametre kadar eş aralıklara bölerek parametre sayısı kadar veriden oluşan bir dizi oluşturur. 

In [21]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [23]:
np.linspace(0,1,6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

Birim matris oluşturma

In [24]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

random içindeki randint, verilen aralıktan rastgele bir sayı çıkartır. aralığın ilk parametresi dahil son parametresi dahil değildir.

In [25]:
np.random.randint(0,10)

8

In [30]:
np.random.randint(0,10)

0

randint içine üç parametre girilebilir. bu durumda verilen aralıktan, üçüncü paramete kadar sayıdan oluşan bir array oluşturulur. 

In [31]:
np.random.randint(1,100,10)

array([22, 23,  3, 26, 37, 56, 46, 21, 31, 51])

randint yerine rand metodu tek parametre ile kullanılabilir. Bu sefer, 0 ile 1 arasından girilen parmetre sayısı kadar rastgele sayı üretilir. 

In [33]:
np.random.rand(5)

array([0.87316712, 0.02936576, 0.33672162, 0.24450312, 0.55712313])

bir diğer metot randn metodudur. Bu metot tek parametre ile kullanılır. Girilen parametre sayısı kadar rakamı, 0' ın etrafından Gauss dağılımına uygun olarak rastgele üretir. 

In [34]:
np.random.randn(10)

array([-0.99278513,  0.2785292 , -0.88476062,  0.66441949,  0.41469388,
        0.60270863, -0.37854975, -1.18515362, -0.87346292, -0.88449357])

In [35]:
np.random.randn(4)

array([-0.27696212, -1.16109996, -1.04243339, -0.29101996])

arange ile oluşturulan bir diziden matris oluşturmak için reshape metodu kullanılır. Fakat dizinin elemanları ile matrisin boyutu uyumlu olmalıdır. 

In [36]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [37]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [38]:
newArray = np.random.randint(1,100,10)

In [39]:
newArray

array([32, 46, 40, 75, 29, 22, 61, 13, 82, 48])

rastgele oluşturulan bu dizinin en büyük elemanını bulmak için max metodu kullanılır. Bunun aksine ne küçük elemanı bulmak içinde min metodu kullanılır. 

In [40]:
newArray.max()

82

In [41]:
newArray.min()

13

sum methodu ile de array' deki elemanların toplamı alınabilir. mean(metodu ile de array' deki elemanların ortalaması alınır: elemanlar toplamı / eleman sayısı

In [42]:
newArray.sum()

448

In [43]:
newArray.mean()

44.8

arraydeki, maximum ve minimum elemanların indis numaraları argmax( ve argmin( metodu ile sorgulanabilir. ))

In [44]:
newArray.argmax()

8

In [45]:
newArray.argmin()

7

matrisin determinantı 

In [46]:
arrx = np.random.randint(1,100,25)

In [47]:
arrx

array([23, 30,  6, 89, 13, 39, 89, 90, 99, 62, 20, 99, 85, 89, 91, 60, 45,
       78, 84, 35, 48, 22, 17, 17, 88])

In [48]:
arrx = arrx.reshape(5,5)

In [49]:
arrx

array([[23, 30,  6, 89, 13],
       [39, 89, 90, 99, 62],
       [20, 99, 85, 89, 91],
       [60, 45, 78, 84, 35],
       [48, 22, 17, 17, 88]])

In [50]:
np.linalg.det(arrx)

-285893512.0000001

In [51]:
arr2 = np.array([[1,2],[3,4]])
arr2

array([[1, 2],
       [3, 4]])

In [52]:
np.linalg.det(arr2)

-2.0000000000000004

In [53]:
round(np.linalg.det(arr2))

-2

In [59]:
round(np.linalg.det(arr2))

-2

# array' lerin indekslenmesi ve parçalanması 

In [60]:
import numpy as np 

In [63]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
arr[2]

2

In [66]:
arr[1:5]

array([1, 2, 3, 4])

In [67]:
arr[:4]

array([0, 1, 2, 3])

In [68]:
arr[::2]

array([0, 2, 4, 6, 8])

In [69]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
arr[:3] = 100
arr

array([100, 100, 100,   3,   4,   5,   6,   7,   8,   9])

In [75]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
arr2 = arr
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
arr2[:3] = 1000
arr2

array([1000, 1000, 1000,    3,    4,    5,    6,    7,    8,    9])

In [78]:
arr

array([1000, 1000, 1000,    3,    4,    5,    6,    7,    8,    9])

arr2' de yapılan değişiklik arr' yi de etkilemiş oldu. bunun olmaması için copy yöntemi kullanılmalıdır. 

In [79]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
arr2 = arr.copy()

In [81]:
arr2[:3] = 1000
arr2

array([1000, 1000, 1000,    3,    4,    5,    6,    7,    8,    9])

In [82]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
narr = np.arange(1,21)
narr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [85]:
narr.reshape(5,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [86]:
narr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [88]:
narr = narr.reshape(5,4)
narr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [89]:
narr[0,0]

1

In [91]:
narr[:,:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18]])

: ile tüm satırları al  ,:2 ile sadece ilk 2 sütunu al 

In [92]:
narr[:3,:3]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

:3 ilk üç satırı al , :3 ilk üç sütunu al 

In [93]:
narr[:2,:]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [94]:
narr[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

array leri filtreleme

In [96]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [98]:
arr > 3

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [99]:
booleanarray = arr > 3

In [100]:
arr[booleanarray]

array([ 4,  5,  6,  7,  8,  9, 10])

In [101]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [102]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

# numpy arraylerinin temel operasyonları 

In [103]:
import numpy as np

In [104]:
arr1 = np.array([10,20,30,40])
arr2 = np.array([1,2,3,4])

In [105]:
arr1 + arr2

array([11, 22, 33, 44])

arraylerin boyutları eşit olmlıdır.

In [106]:
arr1 - arr2

array([ 9, 18, 27, 36])

In [107]:
arr1 * arr2 

array([ 10,  40,  90, 160])

yukarıdaki işlem, Fizik'te iki vektörün sklaer ya da iç çarpımıdır. 

In [108]:
arr1 + 100

array([110, 120, 130, 140])

In [109]:
arr2 - 100

array([-99, -98, -97, -96])

In [110]:
arr1 / 3

array([ 3.33333333,  6.66666667, 10.        , 13.33333333])

In [111]:
np.sqrt(arr1)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532])

In [112]:
arr1

array([10, 20, 30, 40])

numpy' ın tüm özelikleri için Google veya başka bir arama motoru üzerinden numpy documentation sorgusu ile açılan sayfadan inceleme yapılabilir. 